# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default='notes_abt_this_book'),
            preserve_default=False,
        ),
    ]
